export const books = [
  {
    title:
      "Teoria y terapia de la neurosis iniciación a la terapia y al analisis existencial",
    offerPrice: 545,
    price: 800,
    discount: 38,
    available: true,
    description: "",
    rating: 5,
  },
  {
    title:
      "Llegará un día en el que serás libre:  Cartas, textos y discursos inéditos.",
    offerPrice: 443,
    price: 715,
    discount: 38,
    available: true,
    description: "",
    rating: 5,
  },
  {
    title: "Lo que no está escrito en mis libros",
    offerPrice: 660,
    price: 409,
    discount: 38,
    available: true,
    description: "",
    rating: 5,
  },
  {
    title: "Logoterapia y análisis existencial: Textos de seis decadas",
    offerPrice: 498,
    price: 800,
    discount: 38,
    available: true,
    description: "",
    rating: 5,
  },
  {
    title: "Logoterapia y analisis existencial hoy ",
    offerPrice: 744,
    price: 1200,
    discount: 38,
    available: true,
    description: "",
    rating: 5,
  },
  {
    title: "Ante el vacio existencial: Hacia una HUM",
    offerPrice: 313,
    price: 505,
    discount: 38,
    available: true,
    description: "",
    rating: 5,
  },
  {
    title: "Fundamentos y aplicaciones de la logoterapia",
    offerPrice: 313,
    price: 715,
    discount: 38,
    available: true,
    description: "",
    rating: 5,
  },
  {
    title: "Psicoterapia y existencialismo escritos",
    offerPrice: 474,
    price: 765,
    discount: 38,
    available: true,
    description: "",
    rating: 5,
  },
];
